# Generated by Django 3.2.7 on 2021-12-13 14:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentLogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prot_logo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/OceanViewer/files'), upload_to='')),
                ('cds_logo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/OceanViewer/files'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='select_region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accNbr_gb', models.CharField(blank=True, max_length=12, null=True, verbose_name='genbank accession number')),
                ('used_name', models.CharField(default='example_1', max_length=45)),
                ('isRefSeq', models.BooleanField(default=False)),
                ('prot_seq', models.TextField(default='MGG-G', verbose_name='Aligned protein sequence')),
                ('cds_seq', models.TextField(blank=True, verbose_name='CDS')),
            ],
            options={
                'ordering': ['used_name'],
            },
        ),
    ]
