# Generated by Django 3.2.8 on 2022-02-08 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('key', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('queryFasta', models.FilePathField()),
                ('outBlastXML', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='OutBlast',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('definition', models.CharField(max_length=50)),
                ('accession', models.SmallIntegerField()),
                ('identity', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('sbjct_lenght', models.IntegerField()),
                ('hsp_hseq', models.TextField()),
                ('sbjct_start', models.IntegerField()),
                ('sbjct_end', models.IntegerField()),
                ('hseq_transl', models.TextField()),
                ('hsp_qseq', models.TextField()),
                ('query_start', models.IntegerField()),
                ('query_end', models.IntegerField()),
                ('qseq_transl', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OceanFinder.job')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sequence', models.TextField(default='>input seq test\nATGGGG---', verbose_name='input fasta sequence')),
                ('header', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=25)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OceanFinder.job')),
            ],
        ),
    ]
