# Generated by Django 3.2.7 on 2021-12-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputSequence', models.TextField(default='>input seq test\nATGGGG---', verbose_name='input fasta sequence')),
            ],
        ),
        migrations.CreateModel(
            name='outBlastXML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
